### PR TITLE
Item Drop tables added to the object query

### PR DESCRIPTION
**Pull request by savage13**
This adds a table called 'drop_table' (sorry about the name) with `unit_config_name`, `name`, and `data`.  `name` is the actual table name like `Normal2` or `BombArrow_A`.  `data` is in JSON format.  All of the data comes from `drop_tables.json`.

A query on an object add two fields `drop_table` and `drop_tables` which are the specific drop tables used for a Actor and all of the drop tables for a generic Actor of that type (based on `unit_config_name`).

---
This change is [Reviewable](https://reviewable.io/reviews/zeldamods/radar/2)

### CODE REVIEW

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/zeldamods/radar/2)* status: 4 of 8 files reviewed, 16 unresolved discussions (waiting on @savage13)

___
*[build.ts, line 19 at r1](https://reviewable.io/reviews/zeldamods/radar/2#-Mf0Bpas42xCoUBXxe_e:-Mf0Bpat69VFat1-TMEr:b-l517qn) ([raw file](https://github.com/zeldamods/radar/blob/913dd84bfea04121bc8f2318042cd23ea639455d/build.ts#L19)):*
> ```XML
> 
> // Create Special tags for YAML: !obj, !list, !io, !str64
> var objType = new yaml.Type('!obj', { kind: 'mapping', instanceOf: Object,
> ```

The variable can be const. In general anything that can be const should be const. In general const/let is preferred over var.
___
*[build.ts, line 23 at r1](https://reviewable.io/reviews/zeldamods/radar/2#-Mf0BtRA977FbedapFvw:-Mf0BtRBCYLnal4KGKvu:b-7s4sqq) ([raw file](https://github.com/zeldamods/radar/blob/913dd84bfea04121bc8f2318042cd23ea639455d/build.ts#L23)):*
> ```XML
>   construct: function(data: any) { return data; },
> });
> var listType = new yaml.Type('!list', { kind: 'mapping', instanceOf: Object,
> ```

const
___
*[build.ts, line 27 at r1](https://reviewable.io/reviews/zeldamods/radar/2#-Mf0BubR8fXnAz5Ki2yd:-Mf0BubR8fXnAz5Ki2ye:b-7s4sqq) ([raw file](https://github.com/zeldamods/radar/blob/913dd84bfea04121bc8f2318042cd23ea639455d/build.ts#L27)):*
> ```XML
>   construct: function(data: any) { return data; },
> });
> var ioType = new yaml.Type('!io', { kind: 'mapping', instanceOf: Object,
> ```

const
___
*[build.ts, line 31 at r1](https://reviewable.io/reviews/zeldamods/radar/2#-Mf0BwCF2kWUA8FDAioK:-Mf0BwCF2kWUA8FDAioL:b-7s4sqq) ([raw file](https://github.com/zeldamods/radar/blob/913dd84bfea04121bc8f2318042cd23ea639455d/build.ts#L31)):*
> ```XML
>   construct: function(data: any) { return data; },
> });
> var str64Type = new yaml.Type('!str64', { kind: 'scalar', instanceOf: String,
> ```

const
___
*[build.ts, line 37 at r1](https://reviewable.io/reviews/zeldamods/radar/2#-Mf0BztdBL5ASyt-aPCo:-Mf0BztdBL5ASyt-aPCp:bgaagi) ([raw file](https://github.com/zeldamods/radar/blob/913dd84bfea04121bc8f2318042cd23ea639455d/build.ts#L37)):*
> ```XML
> 
> // Add Special Tags to the Default schema (to facilitate reading)
> let schema = yaml.DEFAULT_SCHEMA.extend([ objType, listType, ioType, str64Type ])
> ```

trailing semicolon
___
*[build.ts, line 42 at r1](https://reviewable.io/reviews/zeldamods/radar/2#-Mf0BAXOCxczyKA1oQFc:-Mf0BAXOCxczyKA1oQFd:b-n9emsn) ([raw file](https://github.com/zeldamods/radar/blob/913dd84bfea04121bc8f2318042cd23ea639455d/build.ts#L42)):*
> ```XML
>   let doc : any = null;
>   try {
>     doc = yaml.load(fs.readFileSync( filePath, 'utf-8'), {schema: schema} );
> ```

For consistency, function calls should look like: `f(a, b, c)` with no extra spaces between the parentheses and arguments. Don't bother spending time on fixing this manually though, I think it'd better to just add an ESLint config and reformat everything automatically ;) I'll take care of this later.
___
*[build.ts, line 56 at r1](https://reviewable.io/reviews/zeldamods/radar/2#-Mf0AvqgEaEOMXLkEyi5:-Mf0AvqgEaEOMXLkEyi6:bbtsbso) ([raw file](https://github.com/zeldamods/radar/blob/913dd84bfea04121bc8f2318042cd23ea639455d/build.ts#L56)):*
> ```XML
>     return dropTableUser;
>   }
>   return undefined;
> ```

Returning null makes more sense here. In general, undefined means "this doesn't have a value or this hasn't been assigned yet" whereas null means "this definitely doesn't have a value".
___
*[build.ts, line 72 at r1](https://reviewable.io/reviews/zeldamods/radar/2#-Mf0CRzj1MjVnpAd4kFB:-Mf0CRzj1MjVnpAd4kFC:bj9p90n) ([raw file](https://github.com/zeldamods/radar/blob/913dd84bfea04121bc8f2318042cd23ea639455d/build.ts#L72)):*
> ```XML
>       }
>       let data = {
>         pop: pop,
> ```

IMO `drops` or `items` would be clearer
___
*[build.ts, line 73 at r1](https://reviewable.io/reviews/zeldamods/radar/2#-Mf0CJ4H-hu5vmd6qqGK:-Mf0CJ4H-hu5vmd6qqGL:b-cil69f) ([raw file](https://github.com/zeldamods/radar/blob/913dd84bfea04121bc8f2318042cd23ea639455d/build.ts#L73)):*
> ```XML
>       let data = {
>         pop: pop,
>         n: [dropTable.RepeatNumMin, dropTable.RepeatNumMax],
> ```

I think `repeat_num` would be a clearer name. Or `drop_count_range` / `item_count_range` if you don't like Nintendo's name ;)
___
*[build.ts, line 75 at r1](https://reviewable.io/reviews/zeldamods/radar/2#-Mf0CbRE9KVFZiqnu088:-Mf0CbRE9KVFZiqnu089:b-u6dgxx) ([raw file](https://github.com/zeldamods/radar/blob/913dd84bfea04121bc8f2318042cd23ea639455d/build.ts#L75)):*
> ```XML
>         n: [dropTable.RepeatNumMin, dropTable.RepeatNumMax],
>       };
>       return {name: key, data: JSON.stringify(data)};
> ```

Why does `data` need to be serialised to JSON here?
___
*[build.ts, line 93 at r1](https://reviewable.io/reviews/zeldamods/radar/2#-Mf0HPfRD7OEqyoIKclW:-Mf0HPfSDDdLV3P2e3bL:blnxdbf) ([raw file](https://github.com/zeldamods/radar/blob/913dd84bfea04121bc8f2318042cd23ea639455d/build.ts#L93)):*
> ```XML
>     let tableName = getDropTableNameFromActorLinkFile( filePath );
>     if(tableName) {
>       let key = path.basename( file, '.yml'); // ==> UnitConfigName
> ```

might be clearer to call this `actorName` (because that's what it is)
___
*[build.ts, line 104 at r1](https://reviewable.io/reviews/zeldamods/radar/2#-Mf0IsHoEJEyrzjmO-OY:-Mf0IsHp0X2C0VqSBOGr:b-qr2a1) ([raw file](https://github.com/zeldamods/radar/blob/913dd84bfea04121bc8f2318042cd23ea639455d/build.ts#L104)):*
> ```XML
>     .forEach(name => {
>       let tables = readDropTablesByName( lootTables[name] );
>       tables.forEach((table : any) => table.unit_config_name = name ); // Add UnitConfigName to each table
> ```

I'd prefer "actor" or "actor_name". UnitConfigName as a term is only used in map units
___
*[build.ts, line 116 at r1](https://reviewable.io/reviews/zeldamods/radar/2#-Mf0JOky-N_Z8hanDR3l:-Mf0JOky-N_Z8hanDR3m:bjfrch7) ([raw file](https://github.com/zeldamods/radar/blob/913dd84bfea04121bc8f2318042cd23ea639455d/build.ts#L116)):*
> ```XML
> 
> db.exec(`
>   DROP TABLE IF EXISTS objs;
> ```

This is unnecessary because we always operate on a clean, empty database.
___
*[build.ts, line 142 at r1](https://reviewable.io/reviews/zeldamods/radar/2#-Mf0JXLu7dMaAQYq-bXX:-Mf0JXLu7dMaAQYq-bXY:b-7ropln) ([raw file](https://github.com/zeldamods/radar/blob/913dd84bfea04121bc8f2318042cd23ea639455d/build.ts#L142)):*
> ```XML
> 
> db.exec(`
>    DROP TABLE IF EXISTS drop_table;
> ```

ditto
___
*[build.ts, line 315 at r1](https://reviewable.io/reviews/zeldamods/radar/2#-Mf0Jq0p6Exmh2oTTKS3:-Mf0Jq0p6Exmh2oTTKS4:b-6izh2a) ([raw file](https://github.com/zeldamods/radar/blob/913dd84bfea04121bc8f2318042cd23ea639455d/build.ts#L315)):*
> ```XML
> db.transaction(() => processMaps())();
> 
> function create_drop_table() {
> ```

createDropTable
___
*[app/app.ts, line 160 at r1](https://reviewable.io/reviews/zeldamods/radar/2#-Mf0K1qN8Ce4R2uaXJrj:-Mf0K1qN8Ce4R2uaXJrk:bmy629t) ([raw file](https://github.com/zeldamods/radar/blob/913dd84bfea04121bc8f2318042cd23ea639455d/app/app.ts#L160)):*
> ```XML
>     if(tableName) {
>       if(tableName == "NoDrop") {
>         // Does NoDrop really mean it does not drop anything ?
> ```

no space before `?` in English
___
*[content/ActorLink/Barrel.yml, line 1 at r1](https://reviewable.io/reviews/zeldamods/radar/2#-Mf09HX17_QZfxpJasKB:-Mf09HX17_QZfxpJasKC:b-97claa) ([raw file](https://github.com/zeldamods/radar/blob/913dd84bfea04121bc8f2318042cd23ea639455d/content/ActorLink/Barrel.yml#L1)):*
> ```YAML
> !io
> ```

Did you mean to commit these files? I'd assume no because you only committed a couple few. There are so many ActorLink and DropTable files that I think they should be left out of the repo.

**Comment by savage13** [comment]
> "Why does data need to be serialised to JSON here?"

Attempting to insert the data directly (Object) results in:

`TypeError: SQLite3 can only bind numbers, strings, Buffers, and null`

Other locations in the code use `JSON.stringify( )` to insert Objects into the database: `data`, `drop` and `equip`;

I moved the JSON.stringify() call closer to the database`INSERT` statement.

> Did you mean to commit these files? 

Yes and no. I was not sure how to make these files available to `build.ts`, so I did something that was obviously broken; sorry. I will make a note in the build.ts and possibly in `Readme.md`(?) to identify where the files can be obtained.

Updated commits probably today.

Before I forget, thanks for being detailed in your review and teaching while commenting. Much appreciated.

**Comment by savage13** [comment]
Removed YAML data files and added a command line argument to `build.ts` to specify the location of the YAML files. It adds a dependency to `minimist` library.

**Review by leoetlino — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/zeldamods/radar/2#-:-Mf36Zmg480t9XEP8PQW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @savage13)

**Review by leoetlino — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldamods/radar/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @savage13)

**Pull request merged**
